name       : pdf2djvu
version    : 0.9.18.2
release    : 4
source     :
    - https://github.com/jwilk/pdf2djvu/releases/download/0.9.18.2/pdf2djvu-0.9.18.2.tar.xz : 9ea03f21d841a336808d89d65015713c0785e7295a6559d77771dc795333a9fa
homepage   : https://jwilk.net/software/pdf2djvu
license    : GPL-2.0-only
component  : office.viewers
summary    : pdf2djvu creates DjVu files from PDF files
description: |
    It's able to extract: graphics, text layer, hyperlinks, document outline (bookmarks), metadata (including XMP metadata). 
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(ddjvuapi)
    - pkgconfig(exiv2)
    - pkgconfig(poppler)
    - gettext-devel
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
