name       : pdf2djvu
version    : 0.9.18.2
release    : 2
source     :
    - https://github.com/jwilk/pdf2djvu/releases/download/0.9.18.2/pdf2djvu-0.9.18.2.tar.xz : 9ea03f21d841a336808d89d65015713c0785e7295a6559d77771dc795333a9fa
license    : GPL-2.0-only
component  : office.viewers
summary    : pdf2djvu creates DjVu files from PDF files.
description: |
    It's able to extract: graphics, text layer, hyperlinks, document outline (bookmarks), metadata (including XMP metadata). 
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(exiv2)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(poppler)
    - gettext-devel
setup      : |
    %patch -p1 < $pkgfiles/poppler-22.02-1.patch
    %patch -p1 < $pkgfiles/poppler-22.02-2.patch
    %patch -p1 < $pkgfiles/poppler-22.03.0.patch
    %patch -p1 < $pkgfiles/poppler-22.03-2.patch
    %configure
build      : |
    %make
install    : |
    %make_install
