name       : pdf2djvu
version    : 0.9.19
release    : 6
source     :
    - https://github.com/jwilk/pdf2djvu/releases/download/0.9.19/pdf2djvu-0.9.19.tar.xz : eb45a480131594079f7fe84df30e4a5d0686f7a8049dc7084eebe22acc37aa9a
homepage   : https://jwilk.net/software/pdf2djvu
license    : GPL-2.0-only
component  : office.viewers
summary    : pdf2djvu creates DjVu files from PDF files
description: |
    It's able to extract: graphics, text layer, hyperlinks, document outline (bookmarks), metadata (including XMP metadata). 
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(ddjvuapi)
    - pkgconfig(exiv2)
    - pkgconfig(poppler)
    - gettext-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
